export const LOAD_CATES_SUCCESS = 'LOAD_CATES_SUCCESS';  

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';  

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';  

export const LOAD_PRODUCTS_BY_CATE='LOAD_PRODUCTS_BY_CATE';

export const CREATE_COMMENT_SUCCESS='CREATE_COMMENT_SUCCESS';

export const LOGIN_WEBSITE_FAILED='LOGIN_WEBSITE_FAILED';

export const LOGIN_WEBSITE_SUCCESS='LOGIN_WEBSITE_SUCCESS';

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';

export const CLEAR_ERROR='CLEAR_ERROR';

export const LOAD_CARTS_SUCCESS='LOAD_CARTS_SUCCESS';

export const UPDATE_CART_SUCCESS='UPDATE_CART_SUCCESS';

export const ADD_CART_SUCCESS='ADD_CART_SUCCESS';

export const REMOVE_CART_SUCCESS='REMOVE_CART_SUCCESS';

export const CLEAR_CART_SUCCESS='CLEAR_CART_SUCCESS';

export const RESET_CART_SUCCESS='RESET_CART_SUCCESS';
